# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:   pretty
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate_path: "page:num"

# Setup
title:       Nitin Bhushan
tagline:     ''
description: 'Curious about the dynamics involved
              in a data-driven energy transition,
              I spend my time connecting the dots
              between digitalisation of energy,
              artificial intelligence and machine learning,
              and behavioural sciences.'
url:         "https://nbhushan.github.io"
baseurl:     ''
paginate:    5
markdown:    kramdown


github_username:      nbhushan
linkedin_username:    bhushannitin
email_id:    bhushan.nitin@posteo.net

# About/contact
author:
  name:      Nitin Bhushan
  email:     bhushan.nitin@posteo.net

# Custom vars
version:     1.0.0
