# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:   pretty
plugins: [jekyll-paginate]
paginate_path: "page:num"

# Setup
title:       Nitin Bhushan
tagline:     ''
description: 'meditations on electrical engineering, psychological science,
  machine learning and statistics, and sustainable energy technology
  amongst other things.'
url:         "https://nbhushan.github.io"
baseurl:     ''
paginate:    5
markdown:    kramdown


github_username:      nbhushan
linkedin_username:    bhushannitin


# About/contact
author:
  name:      Nitin Bhushan
  email:     bhushan.nitin@posteo.net

# Custom vars
version:     1.0.0
