# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:   pretty
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate_path: "page:num"

# Setup
title:       Nitin Bhushan
tagline:     ''
description: 'Curious about the dynamics involved in a data-driven transition 
              to a sustainable society, I spend my time connecting the dots 
              between electrical engineering, machine learning (and statistics), 
              sustainable energy technology, and psychological science (environmental psychology).'
url:         "https://nbhushan.github.io"
baseurl:     ''
paginate:    5
markdown:    kramdown


github_username:      nbhushan
linkedin_username:    bhushannitin
email_id:    bhushan.nitin@posteo.net

# About/contact
author:
  name:      Nitin Bhushan
  email:     bhushan.nitin@posteo.net

# Custom vars
version:     1.0.0
