# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:   pretty
plugins: [jekyll-paginate,jekyll-seo-tag]
paginate_path: "blogs/page:num/"

# Setup
title:       Nitin Bhushan
tagline:     'data science | consultant | energy transition'
description: 'Curious about the dynamics involved
              in a data-driven perspective
              to solve practical problems,
              I spend my time connecting the dots
              between digitalisation of industries,
              artificial intelligence,
              statistics and machine learning,
              and behavioural sciences.'
url:         "https://nbhushan.github.io"
baseurl:     ''
paginate:    3
markdown:    kramdown


github_username:      nbhushan
linkedin_username:    bhushannitin
email_id:    bhushan.nitin@posteo.net

# About/contact
author:
  name:      Nitin Bhushan
  email:     bhushan.nitin@posteo.net

# Custom vars
version:     1.0.0
